# Generated by Django 5.1.1 on 2024-09-21 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somy', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'blog')},
        ),
    ]
